import turtle
from turtle import *
turtle.shape("turtle")
color("purple")
begin_fill()
circle(100,extent=90,steps=2)
end_fill()
color("red")
begin_fill()
circle(100,extent=90,steps=2)
end_fill()
color("purple")
begin_fill()
circle(100,extent=90,steps=2)
end_fill()
color("red")
begin_fill()
circle(100,extent=90,steps=2)
end_fill()
