import turtle
from turtle import *
turtle.width(5)
begin_fill()
color("red","orange")
circle(50)
end_fill()
turtle.left(180)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.left(180)
begin_fill()
color("red","orange")
circle(50)
end_fill()
turtle.penup()
turtle.right(90)
turtle.forward(70)
turtle.pendown()
begin_fill()
color("red","purple")
circle(50,180,2)
end_fill()
